apiVersion: apps/v1
kind: Deployment
metadata:
  name: adjust
  labels:
    app: adjust
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adjust
  template:
    metadata:
      labels:
        app: adjust
    spec:
      containers:
      - name: adjust
        image: adjust:0.0.1
        ports:
        - containerPort: 80
